name: Deploy Top-10 App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create bundle
        run: |
          zip -r top10-backend.zip \
            dist \
            package.json \
            package-lock.json

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: top10-backend.zip
          target: /home/ubuntu/
          debug: true

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            APP_DIR=/var/www/top-10-dir/top-10
            BUNDLE=/home/ubuntu/top10-backend.zip

            echo "Prepare app directory"
            sudo mkdir -p $APP_DIR
            sudo chown ${USER}:${USER} $APP_DIR
            cd $APP_DIR

            echo "Remove old build"
            rm -rf dist

            echo "Unzip new build"
            unzip -o $BUNDLE

            # Optional: write env from secret
            if [ -n "${{ secrets.TOP10_ENV_BASE64 }}" ]; then
              echo "${{ secrets.TOP10_ENV_BASE64 }}" | base64 --decode > .env
            fi

            echo "Install production dependencies"
            npm ci --only=production

            echo "Restart PM2"
            pm2 restart analytics-api || pm2 start dist/main.js --name analytics-api

            pm2 save

            echo " Deployment complete "